var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   " x    oo     y               x                                                  ",
   "     xxxxxxxx  oooo                                     xxx                     ",
   "       x!!!!x xxxxxxx  oo                               x!x              xxx    ",
   "        x!!x    x!!!x xxxxxx  oo                        xtx              x!x    ",
   "        xttx     xtx        xxxxx                                xxx     xtx    ",
   "                                 xxxx                            x!x            ",
   "                                                                 xtx            ",
   "               x                r    oooooo    y            xxx                 ",
   "                         o xxxxxxxxxxxxxxxxxxxxxx           x!x      xxx        ",
   "  xx              o xxxxxx                       x          xtx      x!x        ",
   "  x          o xxxx                               x                  xtx        ",
   "  x      o xxx                                     x                            ",
   "  x  @  xx                                          x                           ",
   "  xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x                          ",
   "         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x                         ",
   "         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      xoooooooooooooooooooooooo",
   "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxttxxxxxxttxxxxxttxxxxxttxxxxxttxxxxxttxxxxxttxxxxxttxxxxxttxxxxxttxxxxxttxxxxxttxxxxxttxxxxxxttxxxxxttxxxxxtt",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                 o                                                                                                ",
   "                 x                                                                                                ",
   "                xxx                                                                                               ",
   "             oo x x oo                                                                                            ",
   "            xxxx   xxxx         oooooooooooooooooooooooooo                                                        ",
   "                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ooooooooooooooooooooooooooooooooooo        ",
   "                                                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
   "      ooooooooooooooooooooo                                          x                                            ",
   "     xxxxxxxxxxxxxxxxxxxxxxx                                    xxxxxx                                            ",
   "                                                            xxx                                                   ",
   " ooooooooooooooooooooooooooooo  r                        xxx                                                      ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   xxx                                                           ",
   "                                                xxx                                                               ",
   "                                             xxx                                                                  ",
   "                                          xxx                                                                     ",
   "                                       xxx                                                                        ",
   "x                                   xxx                                                                           ",
   "x  @    oooooooooooooooooooooooxxxx    ooo         y           ooo            y             ooo            y      ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                               x!!!!!!!!x                                                       ",
   "                                               x!!!!!!!!x                                                       ",
   "                                               x!!!!!!!!x                                                       ",
   "                                               x!!!!!!!!x                                                       ",
   "    xxxx                                       x!!!!!!!!x                                                       ",
   "    x!!x                                       x!!!!!!!!x                                                       ",
   "    xttx                                       x!!!!!!!!x                                                       ",
   "                                               x!!!!!!!!x                                                       ",
   "                                               xttttttttx                                                       ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                  xxxx                                                                                          ",
   "                  x!!x                                                                                          ",
   "                  xttx                                                                                          ",
   "                                                                                                                ",
   "        xxxx                                                                                 xxxx               ",
   "        x!!x                                                                                 x!!x               ",
   "        xttx                                                                                 xttx               ",
   "                                                                   xxxx                                         ",
   "                                                                   x!!x                                         ",
   "                                                                   xttx                                         ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "  r   ooooooooo                                                                                                 ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                   ",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!x x                                                                                  ",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!x  x                                                                                 ",
   " xxxxxxxxxxxxxxxxxtttttttttx   x                                                                                ",
   "                                x                                                                               ",
   "                                 x                                                                              ",
   "                                  x                                                                             ",
   "                                   x                                 y       ooooooo                          x ",
   "                                    x                           xxxxxxxxxxxxxxxxxxxxx                           ",
   "                                      xx                       x                                                ",
   "                                           xx                 x                                                 ",
   "                                          xxx                x                             y                  x ",
   "     x                                xxxxx                 x                         xxxxxxx                   ",
   "     x                                                     x                                                    ",
   "     x    @      oooooooooo     xxxxx                     x                                                     ",
   "     xxxxxxxxxxxxxxxxxxxxxxx                             x                                                      ",
   "                                                        x                               x   x                   ",
   "                              ooo        ooo       ooo x                     y          x o x    oooooo x       ",
   "                            xxxxxx      xxxxx     xxxxx                      xxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
